yarnPath: .yarn/releases/yarn-4.9.0.cjs
nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "" # You will need to get a FontAwesome Pro auth token and put it here
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "" # Same here