yarnPath: .yarn/releases/yarn-4.9.0.cjs
nodeLinker: node-modules

npmScopes:
  awesome.me:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_FONTAWESOME_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_FONTAWESOME_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"